dist: focal
notifications:
  email:
    recipients:
    - secure: "iMlOwVX7sfpalA50fnlDGHJbNFxqg5Zlrrx8ouPOBwwWtjHeL+F4faOvH++JcqIDgssQmChlBUSa9QdwGN3rdsEuU/qkUFo4Jp2Y7tj3mhLf8kF3fdPbA+JlCO+C+T+D1/XB8jv8NRvaMvwzTXYrUt1wzeEBmHS9zN9vsoubl9/X28L+iqaBNRqwc8wDkroNbuykrzEBeUewW1vn5/Y7TWoAyhke4j56L/HciJctiapXfziFuoeFgbJ6Y6mFa79hBB06loNOh2Rfvf1e0uqPdr0x9LGziLBGC0Ecio4avpDcGu5qDYmg5LMfJnEeDVE6/dEQXzrVmjF1/H6XzNJqPu81wWcPjN6ZEyLd4vemb4zPR2Yeb7/bPOU43kJw6krwnrJG0tYBylAPM5xpObU3GpkEpQMA+E1Y3j1NqZaSWHkV/o01jXlKci4OkgZmVlYRwJwINktpTY4KvW+YsLpGQFnSjRmprhJ+ZrcwVu6MMC8+rT66OWujrhszjt7rwJgVbamc8I6qx0lvovLCNKia5pYIKRwzXLbfXg2S1qiRQFJmPzCbk0KLN17wLHl80WO8qASKxzksKpGe9eOCgFHmv/d4AVt7CKCXhgs48k3z1IuAx8O/VY3rq1SwnOVSO3xebKyo6IGvw38ehZL1GaK+FvlRyATVB+XznzVV3TQBueE="
    on_success: change
    on_failure: always
  slack:
    rooms:
    - secure: "LvLLbpOke6KghXuaKdcb6qqOCryVM8gG1r1Aqs5vJbua5e2j8K2ZUAW0Nh1ROOoaibAjICZx5kndmPdlmeG8Y3R4ALy4tX6IF4HJkCnjyYF+BLWXIOOq0LNagiXhXjU89uX4hF5rDlTsv9DKHk1kbpG+5RoZu6BDqbsPVKLOh6YkMGJQPT7YAfbQ+sEIlcTLhDyI+rHTYWuV8wekMrcCY3Z0tR0YdqRq4AzF0WtIi4YT9csp4KglU6L41rSlbe4s1Fys13q72HHEccd1lp0iroZjBT12to0lWg9cJ8vA+HOZsHApwV9XLq561qrP4mqIczy16y+5MEcbRg+VPWKxTZV2CT6Yn2cBIgJHvPODC0Hm9XBtmzHZwYRg9y+1DSCL3PQb/tQMAYA+7RygVw1EUOLi2PW/KL8g9c/0tyiRy7WPw6l2WnSlBkoHftK9Jeaexf0gpzGD87f7UO1KZVE9MW9aenzkjlneFBOnFTTPbMwbta781xKRwj6Htw9/OUTPIY+njpK81xBqbaNZXaQT/+m+5m0Q4bqPztm1BB25agS268PgPOgwa/AjsZzqwwSpjlLVRNbvU6lWoYdqq6s8njDQ0L3BIo5bZJ1K8VKibY5dHxa/bxkbEsV1YvzEO4GyniwXizBWagXqW+y83Y06sqemgfnMEBOCoHd0SZKcmbo="
    on_success: change
    on_failure: always
language: python
python:
- '3.8'
script:
- python -m pip install --upgrade pip
- pip install pytest
- pytest
